# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff8f1f0232a62880a73e6b9b010ebd2f"
name = "VerveAR"
handle = "vervear"
application_url = "https://contemporary-walls-historical-current.trycloudflare.com"
embedded = false

[auth]
redirect_urls = [
  "https://contemporary-walls-historical-current.trycloudflare.com/auth/callback",
  "https://contemporary-walls-historical-current.trycloudflare.com/auth/shopify/callback",
  "https://contemporary-walls-historical-current.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = true

[app_preferences]
url = "https://app.vervear.com/"

[build]
dev_store_url = "vervearshop.myshopify.com"
automatically_update_urls_on_dev = true
